### ISSUE TITLE
week3 assignment.py

### ISSUE THREAD

**Issue by Wesley12138** [PaiPai121/Coursera-Natural-Language-Processing-with-Classification-and-Vector-Spaces#1]
229 'X_demeaned = X - np.mean(X)' should be 'X_demeaned = X - np.mean(X, axis = 0)'

**Comment by Wesley12138** [comment]
sorry, it's 227

**Comment by PaiPai121** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you!
        I will correct it.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                战斗包子
                            
                    
                        
                            
                                    邮箱：kunmeigo@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 1/16/2021 16:25，Wesley12138<notifications@github.com> wrote： 



sorry, it's 227

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
